server:
  port: 8888

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: boot.spring.po

spring:
  datasource:
    url: jdbc:mysql://49.234.25.12:3306/act_learn?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    password: root
    password: XIan934792834.
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/process/
    history-level: full
  thymeleaf:
    mode: LEGACYHTML5

logging:
  config: classpath:log4j2.xml



censorwords_path: D:\xxm\edy\myActiviti\src\main\resources\CensorWords.txt

